name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "2.x"

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version:
          - "8.3"
          - "8.4"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-version }}

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: 'echo "::set-output name=directory::$(composer config cache-dir)"'

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v4.1.2"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-cache"

      - name: "Install packages for PHP 8.4"
        if: ${{ matrix.php-version == '8.4' }}
        run: "composer install --ignore-platform-reqs"

      - name: "Run tests"
        if: ${{ matrix.php-version == '8.3' }}
        run: "make -j -O test"

      - name: "Run tests (PHP 8.4)"
        if: ${{ matrix.php-version == '8.4' }}
        run: "make -j -O test-phpunit test-examples"

      - name: "Send code coverage"
        if: ${{ matrix.php-version == '8.3' }}
        uses: codecov/codecov-action@v4.6.0
